version: '3'

services:
  mongo:
    image: docker.io/bitnami/mongodb:5.0
    container_name: mongodb
    restart: always
    env_file: .env.local
    environment:
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
      - MONGODB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGODB_PRIMARY_ROOT_USER=${DB_ROOT_PASSWORD}
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    volumes:
      - mongo-vol:/bitnami
    networks:
      - simplicy

volumes:
  mongo-vol:

networks:
  simplicy: