version: '3'

services:
  mongo:
    image: docker.io/bitnami/mongodb:5.0
    restart: always
    environment:
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_DATABASE=${DB_NAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_PRIMARY_ROOT_USER=${MONGODB_ROOT_USER}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - mongo-vol:/bitnami
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}

volumes:
  mongo-vol: